version: 2
jobs:
  build:
    docker:
      - image: nfhbar/docker-terratest
    working_directory: /go/src/github.com/user
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - ~/caches/app.tar
      - run: dep init
      - run: dep ensure -vendor-only
      - run: cd tests/ && go test -v
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/caches/app.tar
